#version: '3.8'
#services:
#  redis:
#    image: redis:7.0
#    container_name: redis
#    ports:
#      - "6379:6379"
#    command: ["redis-server", "--appendonly", "yes"]
#    volumes:
#      - redis-data:/data
#  orderservice:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: orderservice
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#
#volumes:
#  redis-data: