spring:
  application:
    name: orderservicespring.application.name=orderservice
  docker:
    compose:
      enabled: false
    skip:
      in-tests: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      order-event: order.event
